# Generated by Django 5.2.17 on 2026-10-08 21:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('sales_channel', models.CharField(db_index=True, max_length=20)),
                ('order_date', models.DateField(db_index=True)),
                ('expected_delivery_date', models.DateField(blank=True, db_index=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_order',
                'ordering': ['-order_date', '-created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount__gte', 0)), name='sales_order_discount_gte_0'), models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='sales_order_total_gte_0'), models.CheckConstraint(condition=models.Q(('paid_total__gte', 0)), name='sales_order_paid_total_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('product_name', models.CharField(max_length=150)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.ordermodel')),
            ],
            options={
                'db_table': 'sales_order_item',
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('order', 'product_id'), name='sales_item_unique_product_per_order'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_item_quantity_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.ordermodel')),
            ],
            options={
                'db_table': 'sales_payment',
                'ordering': ['created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sales_payment_amount_gt_0')],
            },
        ),
    ]
