# Generated by Django 5.2.17 on 2026-10-09 14:13

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'expenses_category',
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='expenses_category_name_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField(db_index=True)),
                ('payment_method', models.CharField(max_length=20)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(db_index=True, max_length=10)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategorymodel')),
            ],
            options={
                'db_table': 'expenses_expense',
                'ordering': ['-expense_date', '-created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expenses_expense_amount_gt_0')],
            },
        ),
    ]
